### ISSUE TITLE
Getting TypeError when searching a "shallowRendered" component

### ISSUE THREAD

**Issue by Danno040** [jquense/bill#1]
I'm using your [teaspoon](https://github.com/jquense/teaspoon) package to shallowRender my components for testing, and for some reason, I'm getting this error (from bill) when trying to call find on it:

```
TypeError: Cannot read property 'displayName' of undefined
```

Strangely, it only happens with one of my components, and I'm not sure why.

I've created [a gist](https://gist.github.com/Danno040/8be7b6838b7e3082a682) with the code that's giving me issues.

Edit: Forgot to mention on node v5.0.0

**Comment by jquense** [comment]
just checking...are you sure the Component is not actually undefined? Perhaps an import/export is not actually doing what you expect?

**Comment by Danno040** [comment]
I'm pretty sure the Component is defined. I think the error is caused by having a number (not a string) as the text portion of an element.

Here's the barest boned example that's erroring for me:

``` jsx
import $ from 'teaspoon';
import React from 'react';

class DumbComponent extends React.Component {
    render() {
        let test = 21;
        return (
            <div>{test}</div>
        );
    }
}

describe('Dumb Component', () => {
    // Given input-form then output-form.
    describe('Structure Tests', () => {
        let dumb = $(<DumbComponent/>).shallowRender();
        dumb.find('div');
    });
});
```

**Comment by jquense** [comment]
There is always something new to learn about React's internal rat's nest of a code base!

I'll add a more defensive check there to prevent this, thanks for the heads up

**Comment by Danno040** [comment]
Great!

I tried writing a test in `selection.js`, but oddly, it passed:

``` jsx
it('should match direct descendents with numerical values', () => {
  let cats = 12;
  match('div > a.foo',
    <div>
      <a className='foo'>{cats}</a>
    </div>
  ).length.should.equal(1)
})
```

I trust that you'll be better than I at figuring out what is causing it to break down.

**Comment by jquense** [comment]
ok so I can't repo this :/ I tried both at the teaspoon and bill module tests. Any other insights?

**Comment by Danno040** [comment]
I run my tests against [jsdom](https://github.com/tmpvar/jsdom) instead of an actual browser.

Perhaps that's the source of the issue?
