### ISSUE TITLE
Silently ignores attempts at using #id selector

### ISSUE THREAD

**Issue by wirehead** [jquense/bill#2]
I was playing with teaspoon and was generating some React code that had a few buttons, each with a different id.  I thought that `button#a` would get the button with `id="a"` and `button#b` would get the button with `id="b"`, but both of those selectors kept returning both buttons.

After RTFM, I realized that the `#id` selector wasn't yet implemented.

Obviously, you probably intend to implement this.  But for principle of least surprise, I'd rather it kick out an error for unsupported and/or invalid selectors.  Or at least the documentation contain bolded a note that #id selectors weren't yet implemented, because I'm somewhat assuming that real front-end devs (I'm not one :) ) use #id selectors a decent amount of the time.

**Comment by jquense** [comment]
Thank for the heads up, I had thought that using the usupported #id would throw but it seems that the underlying parser does implement it. I will just add it :P
