### ISSUE TITLE
Cannot resolve module 'react/lib/ReactDOMComponentTree'

### ISSUE THREAD

**Issue by thom-nic** [jquense/bill#5]
I see the following error when running karma + teaspoon tests under phantomjs.  I'm using react v0.14.8.  Bill @ v3.2.2 & Teaspoon v6.3.0.  The top message is just a warning and the bottom one is fatal but they both cropped up at the same time; I'm struggling to track down the source of the actual error but I suspect they may be related.

```
WARNING in ./~/bill/utils.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOMComponentTree' in /Users/thom/dev/voltserver/ops/client/node_modules/bill
 @ ./~/bill/utils.js 18:26-68
08 04 2016 21:00:33.476:WARN [karma]: No captured browser, open http://localhost:9876/
08 04 2016 21:00:33.482:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
08 04 2016 21:00:33.491:INFO [launcher]: Starting browser PhantomJS
08 04 2016 21:00:34.275:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#x5ikoTDwSQyhfF5iAAAA with id 88681715
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Strict mode forbids implicit creation of global property 'isPrimitive'
```

**Comment by jquense** [comment]
no idea about the isPrimitive error I don't think that's me. As for the missing module warning. it's just a warning that's caused by a dynamic require needed to maintain support for 0.14 while also supporting v15 . it's just a heads up, nothing to fix.

**Comment by thom-nic** [comment]
Actually I narrowed this down to a move from teaspoon v6.1.0 to v6.2.0, with no other changes to any source or dependencies.  Although the between those two versions of teaspoon it looks like there's a major version change in bill (2.x to 3.x.)  Would you like me to open a separate issue under that project?

**Comment by jquense** [comment]
What specifically are you reporting here? the missing module isn't a bug...if you mean the isPrimitve error then yeah open up an issue there

**Comment by thom-nic** [comment]
Sorry, yes my karma/phantomJS tests all fail with that `isPrimitive` error when I upgrade teaspoon to v6.2.  I will open an issue in teaspoon.

**Comment by jquense** [comment]
I think if there is a bug its here in bill, sorry. 

But I can't reproduce it. nothing in the code looks like i'd accidently try and set a global var

**Comment by thom-nic** [comment]
Yeah I knew I was not giving much to go on :/  My source maps have not worked in webpack/karma tests but I'll see if I can't resolve that and get more details for you.  Thanks.

**Comment by thom-nic** [comment]
Strangely enough I can't seem to reproduce the issue anymore with the same source tree and package.json from yesterday.  I guess that's my punishment for not using exact version specs in my package.json.  Sorry for the trouble!

**Comment by wbecker** [comment]
I'm still having this issue...

```

WARNING in ./~/bill/utils.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOMComponentTree' in <directory name>/node_modules/bill
```

from webpack when doing karma tests.

Coming from:

```
try {                                                                            
  ReactDOMComponentTree = require('react/lib/ReactDOMComponentTree');            
} catch (err) {} //eslint-disable-line     
```

in bill/utils.js

Bill is `"version": "3.2.1"`

**Comment by wbecker** [comment]
Looks like it is [only in 15](https://github.com/facebook/react/commit/ce528457a49306cf7b0fb4008e9c15aa8d68b93e) (see the tag), so upgrading would get rid of the error message?

**Comment by jquense** [comment]
@wbecker see the note here: https://github.com/jquense/bill#react-compatibility

and yeah upgrading will remove the warning, but its not necessary, you jsut have to live with a warning

**Comment by wbecker** [comment]
It's not the warning that's the problem per se, it's more that due to the warning webpack prints out every chunk it loads (1400+) on a separate line on each karma run!

**Comment by jquense** [comment]
fairly certian you can configure that. I mean I agree it's not ideal, you can pin to a lower version, but the other option was not support react <=0.14 anymore, which I think is worse
